// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) error
	AddBook(ctx context.Context, arg AddBookParams) error
	AddCount(ctx context.Context, arg AddCountParams) error
	AddTimeTable(ctx context.Context, arg AddTimeTableParams) error
	CheckChildDetail(ctx context.Context, childrenID int32) (int64, error)
	CheckFriendsList(ctx context.Context, arg CheckFriendsListParams) ([]CheckFriendsListRow, error)
	CheckUsernameAvailability(ctx context.Context, username string) (int64, error)
	CompairKey(ctx context.Context, randomKey string) (ParentsDetail, error)
	CreateBookHistory(ctx context.Context, arg CreateBookHistoryParams) error
	CreateChild(ctx context.Context, arg CreateChildParams) error
	CreateChildDetail(ctx context.Context, arg CreateChildDetailParams) error
	CreateChildNotification(ctx context.Context, arg CreateChildNotificationParams) error
	CreateChildToken(ctx context.Context, arg CreateChildTokenParams) error
	CreateFriendsLobbyQuestions(ctx context.Context, arg CreateFriendsLobbyQuestionsParams) error
	CreateGameFriendLobby(ctx context.Context, arg CreateGameFriendLobbyParams) error
	CreateGameNotification(ctx context.Context, arg CreateGameNotificationParams) error
	CreateGameRandomLobby(ctx context.Context, arg CreateGameRandomLobbyParams) error
	CreateGeneralVideo(ctx context.Context, arg CreateGeneralVideoParams) error
	CreateParent(ctx context.Context, phone string) error
	CreateParentDetail(ctx context.Context, arg CreateParentDetailParams) error
	CreateParentsNotification(ctx context.Context, arg CreateParentsNotificationParams) error
	CreateParentsToken(ctx context.Context, arg CreateParentsTokenParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) error
	CreatePaymentNumber(ctx context.Context, arg CreatePaymentNumberParams) error
	CreateQuestions(ctx context.Context, arg CreateQuestionsParams) error
	CreateQueue(ctx context.Context, arg CreateQueueParams) error
	CreateRandomLobbyQuestions(ctx context.Context, arg CreateRandomLobbyQuestionsParams) error
	CreateSaveBook(ctx context.Context, arg CreateSaveBookParams) error
	CreateScore(ctx context.Context, arg CreateScoreParams) error
	CreateVideo(ctx context.Context, arg CreateVideoParams) error
	DeleteChildNotification(ctx context.Context, id int32) error
	DeleteGameFriendLobby(ctx context.Context, id int32) error
	DeleteGameNotification(ctx context.Context, arg DeleteGameNotificationParams) error
	DeleteGameRandomLobby(ctx context.Context, id int32) error
	EditChildDetail(ctx context.Context, arg EditChildDetailParams) error
	EditParentDetail(ctx context.Context, arg EditParentDetailParams) error
	FetchBookAfterCreated(ctx context.Context, randomunique string) (Book, error)
	FetchBookById(ctx context.Context, id int32) (FetchBookByIdRow, error)
	FetchBookContent(ctx context.Context, id int32) (sql.NullString, error)
	FetchBookCount(ctx context.Context, bookID int32) (int32, error)
	FetchBookDetailsById(ctx context.Context, id int32) (FetchBookDetailsByIdRow, error)
	FetchBookHistory(ctx context.Context, arg FetchBookHistoryParams) (BookHistory, error)
	FetchBookHistoryList(ctx context.Context, arg FetchBookHistoryListParams) ([]BookHistory, error)
	FetchBookListBySection(ctx context.Context, arg FetchBookListBySectionParams) ([]FetchBookListBySectionRow, error)
	FetchBookListHome(ctx context.Context, id int32) ([]FetchBookListHomeRow, error)
	FetchNewBook(ctx context.Context) ([]FetchNewBookRow, error)
	FetchPopularBook(ctx context.Context) ([]FetchPopularBookRow, error)
	FetchPopularBookListBySection(ctx context.Context, section string) ([]FetchPopularBookListBySectionRow, error)
	FetchSavedBook(ctx context.Context, arg FetchSavedBookParams) (BookSaved, error)
	FetchSavedBookList(ctx context.Context, arg FetchSavedBookListParams) ([]BookSaved, error)
	GetChild(ctx context.Context, username string) (GetChildRow, error)
	GetChildDetail(ctx context.Context, childrenID int32) (ChildrenDetail, error)
	GetChildDetailListOnCountry(ctx context.Context, country sql.NullString) ([]ChildrenDetail, error)
	GetChildDetailListOnState(ctx context.Context, state sql.NullString) ([]ChildrenDetail, error)
	GetChildForVerify(ctx context.Context, id int32) (Child, error)
	GetChildNotification(ctx context.Context, userID int32) ([]ChildNotification, error)
	GetChildToken(ctx context.Context, userID int32) (ChildToken, error)
	GetChildrenDetails(ctx context.Context, parentID int32) ([]GetChildrenDetailsRow, error)
	GetClassVideo(ctx context.Context, class int32) ([]Video, error)
	GetClassVideoFree(ctx context.Context, class int32) ([]Video, error)
	GetFakeGameRandomLobbyByClass(ctx context.Context, class int32) (GameRandomLobby, error)
	GetFriend(ctx context.Context, arg GetFriendParams) (Friend, error)
	GetFriendsList(ctx context.Context, arg GetFriendsListParams) ([]GetFriendsListRow, error)
	GetFriendsLobbyQuestions(ctx context.Context, lobbyID int32) ([]FriendsLobbyQuestion, error)
	GetGameFriendLobby(ctx context.Context, arg GetGameFriendLobbyParams) (GameFriendLobby, error)
	GetGameNotification(ctx context.Context, userID int32) ([]GameNotification, error)
	GetGameRandomLobby(ctx context.Context, arg GetGameRandomLobbyParams) (GameRandomLobby, error)
	GetGameRandomLobbyById(ctx context.Context, id int32) (GameRandomLobby, error)
	GetGeneralVideo(ctx context.Context, id int32) (GeneralVideo, error)
	GetListGeneralVideo(ctx context.Context) ([]GeneralVideo, error)
	GetOwnQueueInfo(ctx context.Context, userID int32) (GameQueue, error)
	GetParent(ctx context.Context, phone string) (GetParentRow, error)
	GetParentByRandomKey(ctx context.Context, randomKey string) (GetParentByRandomKeyRow, error)
	GetParentDetail(ctx context.Context, parentID int32) (ParentsDetail, error)
	GetParentForLogin(ctx context.Context, phone string) (GetParentForLoginRow, error)
	GetParentId(ctx context.Context, id int32) (int32, error)
	GetParentInfo(ctx context.Context, phone string) (Parent, error)
	GetParentsNotification(ctx context.Context, userID int32) ([]ParentsNotification, error)
	GetParentsToken(ctx context.Context, userID int32) (ParentsToken, error)
	GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error)
	GetPaymentList(ctx context.Context, arg GetPaymentListParams) ([]Payment, error)
	GetPaymentNumberInfo(ctx context.Context, parentID int32) (PaymentNumber, error)
	GetQuestions(ctx context.Context, arg GetQuestionsParams) ([]GameQuestion, error)
	GetQueue(ctx context.Context, arg GetQueueParams) (GameQueue, error)
	GetRandomLobbyQuestions(ctx context.Context, lobbyID int32) ([]RandomLobbyQuestion, error)
	GetScore(ctx context.Context, arg GetScoreParams) (GamePoint, error)
	GetScoreList(ctx context.Context, arg GetScoreListParams) ([]GamePoint, error)
	GetSubjectVideo(ctx context.Context, arg GetSubjectVideoParams) ([]Video, error)
	GetSubjectVideoFree(ctx context.Context, arg GetSubjectVideoFreeParams) ([]Video, error)
	GetTimeTable(ctx context.Context, childrenID int32) ([]TimeTable, error)
	GetVideo(ctx context.Context, id int32) (Video, error)
	RejectFriendRequest(ctx context.Context, id int32) error
	RemoveChildToken(ctx context.Context, userID int32) error
	RemoveOTP(ctx context.Context, phone string) error
	RemoveParentsToken(ctx context.Context, userID int32) error
	RemoveQueue(ctx context.Context, userID int32) error
	RemoveTimeTableAll(ctx context.Context, childrenID int32) error
	RemoveTimeTableByDescription(ctx context.Context, description string) error
	RemovedSavedBook(ctx context.Context, id int32) error
	SaveOTP(ctx context.Context, arg SaveOTPParams) error
	Savepassword(ctx context.Context, arg SavepasswordParams) error
	SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) error
	SetVerification(ctx context.Context, phone string) error
	SetVerificationChild(ctx context.Context, parentID int32) error
	UpdateBook(ctx context.Context, arg UpdateBookParams) error
	UpdateBookCount(ctx context.Context, arg UpdateBookCountParams) error
	UpdateBookHistory(ctx context.Context, arg UpdateBookHistoryParams) error
	UpdateChildToken(ctx context.Context, arg UpdateChildTokenParams) error
	UpdateGameFriendLobby(ctx context.Context, arg UpdateGameFriendLobbyParams) error
	UpdateGameRandomLobby(ctx context.Context, arg UpdateGameRandomLobbyParams) error
	UpdateParentsToken(ctx context.Context, arg UpdateParentsTokenParams) error
	UpdateQueue(ctx context.Context, arg UpdateQueueParams) error
	UpdateQueueLobby(ctx context.Context, arg UpdateQueueLobbyParams) error
	UpdateScorePlayerOne(ctx context.Context, arg UpdateScorePlayerOneParams) error
	UpdateScorePlayerTwo(ctx context.Context, arg UpdateScorePlayerTwoParams) error
}

var _ Querier = (*Queries)(nil)
