// Code generated by sqlc. DO NOT EDIT.
// source: random_lobby_questions.sql

package db

import (
	"context"
)

const createRandomLobbyQuestions = `-- name: CreateRandomLobbyQuestions :exec
INSERT INTO random_lobby_questions(
   lobby_id, questions,options_a,options_b,options_c,options_d,correct_options
) VALUES (
    ?,?,?,?,?,?,?
)
`

type CreateRandomLobbyQuestionsParams struct {
	LobbyID        int32  `json:"lobby_id"`
	Questions      string `json:"questions"`
	OptionsA       string `json:"options_a"`
	OptionsB       string `json:"options_b"`
	OptionsC       string `json:"options_c"`
	OptionsD       string `json:"options_d"`
	CorrectOptions string `json:"correct_options"`
}

func (q *Queries) CreateRandomLobbyQuestions(ctx context.Context, arg CreateRandomLobbyQuestionsParams) error {
	_, err := q.exec(ctx, q.createRandomLobbyQuestionsStmt, createRandomLobbyQuestions,
		arg.LobbyID,
		arg.Questions,
		arg.OptionsA,
		arg.OptionsB,
		arg.OptionsC,
		arg.OptionsD,
		arg.CorrectOptions,
	)
	return err
}

const getRandomLobbyQuestions = `-- name: GetRandomLobbyQuestions :many
SELECT id, lobby_id, questions, options_a, options_b, options_c, options_d, correct_options FROM random_lobby_questions WHERE lobby_id = ?
`

func (q *Queries) GetRandomLobbyQuestions(ctx context.Context, lobbyID int32) ([]RandomLobbyQuestion, error) {
	rows, err := q.query(ctx, q.getRandomLobbyQuestionsStmt, getRandomLobbyQuestions, lobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RandomLobbyQuestion
	for rows.Next() {
		var i RandomLobbyQuestion
		if err := rows.Scan(
			&i.ID,
			&i.LobbyID,
			&i.Questions,
			&i.OptionsA,
			&i.OptionsB,
			&i.OptionsC,
			&i.OptionsD,
			&i.CorrectOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
