// Code generated by sqlc. DO NOT EDIT.
// source: token.sql

package db

import (
	"context"
)

const removeChildToken = `-- name: RemoveChildToken :exec
DELETE FROM child_token WHERE user_id=?
`

func (q *Queries) RemoveChildToken(ctx context.Context, userID int32) error {
	_, err := q.exec(ctx, q.removeChildTokenStmt, removeChildToken, userID)
	return err
}

const removeParentsToken = `-- name: RemoveParentsToken :exec
DELETE FROM parents_token WHERE user_id=?
`

func (q *Queries) RemoveParentsToken(ctx context.Context, userID int32) error {
	_, err := q.exec(ctx, q.removeParentsTokenStmt, removeParentsToken, userID)
	return err
}
